engines:
  duplication:
    enabled: true
    config:
      languages:
        - python
  radon:
    enabled: true
    config:
      threshold: "B"
  pep8:
    enabled: true

ratings:
  paths:
    - "**.py"

exclude_paths:
  - auxlib/_vendor/**/*
  - tests/**/*
