language: python
python: "3.5"
sudo: false
env:
  global:
    - PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
    - secure: "vbmp+Jid6vuRUQsTMKiJprbW4T0N4WmAPfkEEmc1PsriH+99fXV8PEwaitEdhBNgrmAf1bFV7mtpuVfUEVeGgND3RVND9LUj/ep/+MFc5gFY6OmqcPngn7vcST5RTpoDqGX7hBrjpP55szwCwB8Vklo5IXZUxHL7hOT+blbkWvc="
  matrix:
    - TOXENV=py27
    - TOXENV=py34
    - TOXENV=py35
    - TOXENV=pypy
    # - TOXENV=pypy3  # has a test error with __package__ https://bitbucket.org/pypy/pypy/issues/1889/attributeerror-importing-module
    - TOXENV=codequality

before_install:
  - python --version
  - printenv
  - uname -a

install: travis_retry pip install -U tox

script:
  - tox -v

after_success:
  - travis_retry pip install codecov codacy-coverage
  - codecov --env TOX_ENV
  - python-codacy-coverage -r coverage.xml
