language: python

python:
  - "2.7"
  - "pypy"

env:
  global:
    TRAVISCI_ENABLED=1
  matrix:
    - TOXENV=py27
    - TOXENV=pypy

before_install:
  - |
    python --version
    printenv
    uname -a
    lsb_release -a

install:
  - pip install tox

script:
  - tox

after_success:
  - .tox/$TRAVIS_PYTHON_VERSION/bin/coveralls
