language: python
python: "3.5"
env:
  global:
    - PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
  matrix:
    - TOXENV=py27
    - TOXENV=py34
    - TOXENV=py35
    - TOXENV=pypy
    # - TOXENV=pypy3  # has a test error with __package__ https://bitbucket.org/pypy/pypy/issues/1889/attributeerror-importing-module
    - TOXENV=codequality

before_install:
  - python --version
  - printenv
  - uname -a
  - lsb_release -a

cache:
  - $HOME/.pip-cache

install:
  - pip install tox

script:
  - tox -v

after_success:
    - pip install codecov
    - codecov