language: python

python: 2.7

env:
  global:
    TRAVISCI_ENABLED=1
  matrix:
    - TOXENV=2.7

before_install:
  - |
    python --version
    printenv
    uname -a
    lsb_release -a

install:
  - pip install tox

script:
  - tox -v -- -v

after_success:
  - .tox/$TRAVIS_PYTHON_VERSION/bin/coveralls
